const KEY="rph202-final-mastery-v1",state=JSON.parse(localStorage.getItem(KEY)||'{"seen":{},"wrong":{},"correct":0,"total":0}');let session=[],idx=0,answered=false,timerSeconds=1500,timerRun=false,tick;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),work=id=>WORKS.find(w=>w.id===id),shuffle=a=>[...a].sort(()=>Math.random()-.5);
function view(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='home')home();if(id==='works')showWork(WORKS[0].id);if(id==='timeline')timeline();if(id==='review')review();if(id==='exam')essay();scrollTo(0,0)}
function home(){let seen=Object.keys(state.seen).length,mastery=Math.round((state.correct/Math.max(1,state.total))*Math.min(1,seen/QUESTIONS.length)*100);document.querySelector('#mastery').textContent=mastery+'%';document.querySelector('#seen').textContent=`${seen}/${QUESTIONS.length}`;document.querySelector('#accuracy').textContent=state.total?Math.round(state.correct/state.total*100)+'%':'—';document.querySelector('#mistakes').textContent=Object.keys(state.wrong).length;document.querySelector('#workGrid').innerHTML=WORKS.map(w=>`<button class="card" data-work="${w.id}"><span class="year">${w.year}</span><h3>${w.title}</h3><small>${w.author}<br>${w.period}</small><span class="tags">${w.tags.map(t=>`<i class="tag">${t}</i>`).join('')}</span></button>`).join('');document.querySelectorAll('[data-work]').forEach(b=>b.onclick=()=>{view('works');showWork(b.dataset.work)})}
function showWork(id){let w=work(id);document.querySelector('#workDetail').innerHTML=`<article class="workhero"><p class="eyebrow">${w.year} · ${w.genre}</p><h2>${w.title}</h2><p>${w.author} · ${w.period}</p><button data-practice="${id}">Practice this block</button></article><div class="columns"><article class="panel"><h2>Distinctions</h2><ul>${w.characters.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="panel"><h2>Required examples</h2><ol>${w.events.map(x=>`<li>${x}</li>`).join('')}</ol></article><article class="panel"><h2>Key relationships</h2><ul>${w.themes.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="panel"><h2>Method and traps</h2><p>${w.form}</p><ul>${w.symbols.map(x=>`<li>${x}</li>`).join('')}</ul></article></div>`;document.querySelector('[data-practice]').onclick=()=>start(shuffle(QUESTIONS.filter(q=>q.work===id||q.work==='all')))}
function timeline(){document.querySelector('#timelineList').innerHTML=WORKS.map(w=>`<article><b>${w.year}</b><h2>${w.title}</h2><p>${w.period} · ${w.genre}</p></article>`).join('');document.querySelector('#compareGrid').innerHTML=`<article><h2>Structural question</h2><p>What is ultimate reality? → How does the cosmos arise? → What is the human problem? → How is it overcome or saved?</p></article><article><h2>Exam rule</h2><p>Connect every concept to a tradition, an exact example and a consequence for human life.</p></article>`}
function start(items){session=items.length?items:shuffle(QUESTIONS).slice(0,15);idx=0;view('practice');render()}
function smart(){let weak=QUESTIONS.filter(q=>state.wrong[q.id]),fresh=QUESTIONS.filter(q=>!state.seen[q.id]);start([...shuffle(weak),...shuffle(fresh),...shuffle(QUESTIONS)].filter((q,i,a)=>a.findIndex(x=>x.id===q.id)===i).slice(0,15))}
function render(){answered=false;let q=session[idx];document.querySelector('#counter').textContent=`${idx+1}/${session.length}`;document.querySelector('#qmeta').textContent=q.work==='all'?'COMPARATIVE':work(q.work).title;document.querySelector('#prompt').textContent=q.prompt;document.querySelector('#feedback').textContent='';document.querySelector('#next').classList.add('hidden');let a=document.querySelector('#answers');if(q.type==='short'){a.innerHTML='<textarea class="short" placeholder="Answer in English without notes…"></textarea><button id="checkShort">Check response</button>';document.querySelector('#checkShort').onclick=()=>gradeShort(q)}else{a.innerHTML=q.options.map((o,i)=>`<button class="option" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('');a.querySelectorAll('.option').forEach(b=>b.onclick=()=>grade(q,Number(b.dataset.i),b))}}
function grade(q,n,b){if(answered)return;answered=true;state.total++;state.seen[q.id]=1;let ok=n===q.answer;if(ok){state.correct++;delete state.wrong[q.id]}else state.wrong[q.id]=(state.wrong[q.id]||0)+1;document.querySelectorAll('.option').forEach((x,i)=>x.classList.toggle('correct',i===q.answer));if(!ok)b.classList.add('wrong');document.querySelector('#feedback').innerHTML=`<b>${ok?'Correct':'Review this'}</b><br>${q.why}`;document.querySelector('#next').classList.remove('hidden');save()}
function gradeShort(q){if(answered)return;answered=true;let text=document.querySelector('.short').value.toLowerCase(),hits=q.answer.filter(k=>text.includes(k)).length;state.total++;state.seen[q.id]=1;if(hits>=2){state.correct++;delete state.wrong[q.id]}else state.wrong[q.id]=(state.wrong[q.id]||0)+1;document.querySelector('#feedback').innerHTML=`<b>You included ${hits}/${q.answer.length} key ideas.</b><br>${q.why}<br><small>Keywords: ${q.answer.join(', ')}</small>`;document.querySelector('#next').classList.remove('hidden');save()}
function review(){let ids=Object.keys(state.wrong);document.querySelector('#reviewList').innerHTML=ids.length?ids.map(id=>{let q=QUESTIONS.find(x=>x.id===id);return `<article class="reviewitem"><p class="eyebrow">${q.work==='all'?'Comparative':work(q.work).title}</p><h3>${q.prompt}</h3><p>${q.why}</p><button data-retry="${id}">Retry</button></article>`}).join(''):'<div class="alert">No recorded mistakes yet. Start a practice session.</div>';document.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>start([QUESTIONS.find(q=>q.id===b.dataset.retry)]))}
function essay(){document.querySelector('#essayLab').innerHTML=`<h2>Comparative answer lab</h2>${ESSAYS.map((e,i)=>`<div class="thesis"><b>${i+1}. ${e}</b><p>Define both concepts → identify the tradition and example → explain the similarity or difference → conclude which religious problem each resolves.</p></div>`).join('')}<p><b>Method:</b> precise term · exact example · contrast · significance.</p>`}
document.addEventListener('click',e=>{let b=e.target.closest('[data-view],[data-action]');if(!b)return;if(b.dataset.view)view(b.dataset.view);if(b.dataset.action==='smart')smart();if(b.dataset.action==='exam')start(shuffle(QUESTIONS).slice(0,30))});document.querySelector('#next').onclick=()=>{if(++idx>=session.length)view('home');else render()};document.querySelector('#timer').onclick=()=>{timerRun=!timerRun;clearInterval(tick);if(timerRun)tick=setInterval(()=>{timerSeconds--;let m=Math.floor(timerSeconds/60),s=timerSeconds%60;document.querySelector('#timer').textContent=`${m}:${String(s).padStart(2,'0')}`;if(timerSeconds<=0){clearInterval(tick);timerRun=false;timerSeconds=1500}},1000)};home();essay();
